### ISSUE TITLE
BUG compilation ?

### ISSUE THREAD

**Issue by AssociationSirius** [katajakasa/SDL_kitchensink#20]
I have fatal issu when i try to compile SDL_kitchensink:

In function ‘_HandleBitmapSubtitle’:

```
/SDL_kitchensink-master/src/kitplayer.c:498:17: 
error: ‘AVSubtitleRect {aka struct AVSubtitleRect}’ has no member named ‘data’
 rect->data[0],
```

```
/src/kitplayer.c:500:17: 
error: ‘AVSubtitleRect {aka struct AVSubtitleRect}’ has no member named ‘linesize’
 rect->linesize[0],
```

```
SDL_kitchensink-master/src/kitplayer.c:503:66:
 error: ‘AVSubtitleRect {aka struct AVSubtitleRect}’ has no member named ‘data’
SDL_SetPaletteColors(s->format->palette, (SDL_Color*)rect->data[1], 0, 256);
```

Cordially

**Comment by katajakasa** [comment]
Update to ffmpeg 3.0

**Comment by katajakasa** [comment]
Note btw that commit e343927523c743970d1db008400012f84b00f181 should work with ffmpeg 2.8, if required :)

**Comment by rmoog** [comment]
ffmpeg 3.0 and newer still break a couple packages. See https://bugs.gentoo.org/show_bug.cgi?id=574788

**Comment by rmoog** [comment]
ffmpeg 3.x is not available in FreeBSD 11.0 either

**Comment by katajakasa** [comment]
That is fine. My interest is currently in supporting windows/msys2 and debian sid systems (as those are the ones that I use).

**Comment by rmoog** [comment]
Now that ffmpeg 3.2 is on FreeBSD 11.0, SDL_kitchensink also builds on it.
